//Errors of GSM

#define COMMUNITE_ERROR             -1 
#define NO_SIM_CARD_ERROR           -2
#define SIM_CARD_NO_REG_ERROR       -3
#define CALL_ERROR                  -4
#define AT_CPMS_ERROR               -5
#define AT_CMGF_ERROR               -6
#define AT_CSCS_ERROR               -7
#define AT_CMGS_ERROR               -8
#define END_CHAR_ERROR              -9
#define AT_CGATT_ERROR              -11
#define AT_CGACT_ERROR              -12
#define AT_CIPSTART_ERROR           -13
#define AT_CIPSEND_ERROR            -14
#define AT_CIPMUX_ERROR             -15
#define AT_CIPQSEND_ERROR           -16
#define AT_CSTT_ERROR               -17
#define AT_CIICR_ERROR              -18
#define AT_CGATT1_ERROR             -50
#define EAT0_ERROR                  -51
#define AT_SAPBR_ERROR                      -52
#define DEACTIVATE_BEARER_PROFILE_ERROR          -53
#define AT_SAPBR_GPRS_ERROR                      -54
#define AT_SAPBR_APN_ERROR                       -55
#define AT_SAPBR_OPEN_ERROR                      -56
#define AT_SAPBR_QUERY_ERROR                     -57
#define AT_HTTPINTI_ERROR                       -58
#define AT_HTTPSSL_ERROR                        -59
#define AT_HTTPPARA_ERROR                       -60
#define AT_HTTPARA_URL_ERROR                    -61
#define AT_HTTPACTION_ERROR                     -62
#define AT_HTTPREAD_ERROR                       -63
#define AT_HTTPARA_CONTENT_JSON_ERROR           -64
#define AT_HTTPDATA_ERROR                       -65